// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsgokqrybhsblcvrcyht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZ29rcXJ5YmhzYmxjdnJjeWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzMxNjAsImV4cCI6MjA2MzkwOTE2MH0.Rz3_QNeRVFnLfQiAkHakT51xONhbHvJ8CKqVk6N6y2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);